trigger: none

schedules:
- cron: "0 7 * * *"
  displayName: Daily Run 7AM UTC
  branches:
    include:
    - master
  always: true

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true # so we can push commits later
  displayName: Checkout sources

- powershell: .\export.ps1
  displayName: Run export
  env:
    # pass secure variables to the script
    AAD_USERNAME: $(AAD_USERNAME) 
    AAD_PASSWORD: $(AAD_PASSWORD)

- task: PublishPipelineArtifact@1
  displayName: Publish sources
  condition: always()
  continueOnError: true
  inputs:
    targetPath: $(Build.SourcesDirectory)\artifacts
    artifactName: Export